version: '3'

services:
  app:
    image: node:14.15.4-alpine3.10
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
    command: npm run start
    working_dir: "/usr/src/app"
    tty: true
